
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./(components)/nav.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ticket management",
  description: "Generated by Dival",
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto">{children}</div>
        </div>
      </body>
    </html> 
  );
}
